export const Data = [
  {
    id: 1,
    category: "lunch",
    img: "https://i.ibb.co/2h9WR2Z/lunch6.png",
    title: "Healthy Meal Plan",
    text: "Stay healthy, Eat healthy",
    price: "23.99",
  },
  {
    id: 2,
    category: "lunch",
    img: "https://i.ibb.co/fXybM2W/lunch5.png",
    title: "Fried Chicken Bento",
    text: "Stay healthy, Eat healthy",
    price: "9.99",
  },
  {
    id: 3,
    category: "lunch",
    img: "https://i.ibb.co/dQZMDBm/lunch4.png",
    title: "Tarrangon-Rubbed-Salmon",
    text: "Stay healthy, Eat healthy",
    price: "6.99",
  },
  {
    id: 4,
    category: "lunch",
    img: "https://i.ibb.co/M5DLmvz/lunch3.png",
    title: "Indian Lunch",
    text: "Stay healthy, Eat healthy",
    price: "8.99",
  },
  {
    id: 5,
    category: "lunch",
    img: "https://i.ibb.co/rpK9X6d/lunch1.png",
    title: "Beef Steak",
    text: "Stay healthy, Eat healthy",
    price: "15.99",
  },
  {
    id: 6,
    category: "lunch",
    img: "https://i.ibb.co/d7ykRXd/lunch2.png",
    title: "Honey-Soy-Glazed Salmon with Peppers",
    text: "Stay healthy, Eat healthy",
    price: "7.99",
  },
];
